-- Database Schema for Intelligent Invoicing (Updated with Seeds)

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS password_resets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    unit_price DECIMAL(10, 2) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoices (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    client_id INTEGER REFERENCES clients(id) ON DELETE SET NULL,
    status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'paid', 'overdue')),
    due_date DATE,
    total DECIMAL(10, 2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS invoice_items (
    id SERIAL PRIMARY KEY,
    invoice_id INTEGER REFERENCES invoices(id) ON DELETE CASCADE,
    description TEXT NOT NULL,
    quantity DECIMAL(10, 2) DEFAULT 1,
    unit_price DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS emails (
    id SERIAL PRIMARY KEY,
    invoice_id INTEGER REFERENCES invoices(id) ON DELETE CASCADE,
    type VARCHAR(50) CHECK (type IN ('invoice', 'reminder')),
    content TEXT,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed Data (Only runs if data doesn't exist, roughly)
-- Password for demo@example.com is 'demo123'
-- Hash: $2a$10$w.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1 (Use a valid one generated by the app if this fails, or use the registration form)
INSERT INTO users (email, password_hash, email_verified)
VALUES ('demo@example.com', '$2y$10$zPkNlIq8.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1', TRUE)
ON CONFLICT (email) DO NOTHING;

-- Inserting fake clients
INSERT INTO clients (user_id, name, email, address)
SELECT id, 'Acme Corp', 'contact@acme.com', '123 Industrial Way, Looney Tunes, CA'
FROM users WHERE email = 'demo@example.com'
UNION ALL
SELECT id, 'Globex Corporation', 'hank@globex.com', '456 Cypress Creek'
FROM users WHERE email = 'demo@example.com'
UNION ALL
SELECT id, 'Soylent Corp', 'people@soylent.green', '2022 Future St, NYC'
FROM users WHERE email = 'demo@example.com';

-- Inserting fake products
INSERT INTO products (user_id, name, unit_price, description)
SELECT id, 'Web Design', 1500.00, 'Full website design and mockup'
FROM users WHERE email = 'demo@example.com'
UNION ALL
SELECT id, 'SEO Optimization', 500.00, 'Monthly SEO maintenance'
FROM users WHERE email = 'demo@example.com'
UNION ALL
SELECT id, 'Consulting', 200.00, 'Hourly consulting rate'
FROM users WHERE email = 'demo@example.com';
